/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a learner account */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a revocable login session */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active lessons */
        get: operations["listLessons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lessonId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: components["parameters"]["LessonId"];
            };
            cookie?: never;
        };
        /** Get a lesson and active subtopics */
        get: operations["getLesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a test from a versioned configuration
         * @description Fails safely when no eligible PUBLISHED inventory exists.
         */
        post: operations["createTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/{testId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                testId: components["parameters"]["TestId"];
            };
            cookie?: never;
        };
        /**
         * Get owner-scoped test metadata
         * @description This resource never contains question answer keys.
         */
        get: operations["getTest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/{testId}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                testId: components["parameters"]["TestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an attempt for a frozen test */
        post: operations["startAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{attemptId}/next": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        /**
         * Get the next unanswered frozen question
         * @description Uses the answer-key-free AttemptQuestion schema.
         */
        get: operations["getNextAttemptQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{attemptId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit one answer transactionally
         * @description Commits answer, mastery, Error Review and SRS effects atomically.
         */
        post: operations["submitAttemptAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{attemptId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete and score an attempt */
        post: operations["completeAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{attemptId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        /** Get a completed attempt result */
        get: operations["getAttemptResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List mistake groups and spaced-review concepts */
        get: operations["listReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        /**
         * Open one frozen review item
         * @description Feedback is hidden until retry or an audited explicit reveal.
         */
        get: operations["getReviewItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{reviewId}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a retrieval-practice retry
         * @description Resolution evidence only; original score/mastery/SRS evidence is unchanged.
         */
        post: operations["gradeReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{reviewId}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explicitly reveal and audit feedback
         * @description Reveal alone does not resolve the review item.
         */
        post: operations["revealReviewAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{reviewId}/mark": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Mark or unmark a review item */
        put: operations["setReviewMark"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mastery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current mastery with confidence and coverage */
        get: operations["getMastery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get persisted mastery snapshots and trend completeness */
        get: operations["getProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one aggregated learning-dashboard resource */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/next-actions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the highest-priority safe learner action */
        get: operations["getCurrentNextAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a heavy analytics rebuild or backfill */
        post: operations["createAnalyticsJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** Get heavy analytics job state */
        get: operations["getAnalyticsJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search and filter the question bank */
        get: operations["listAdminQuestions"];
        put?: never;
        /** Create a DRAFT question */
        post: operations["createAdminQuestionDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Create an immutable question revision */
        patch: operations["createAdminQuestionRevision"];
        trace?: never;
    };
    "/admin/questions/{questionId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve reject or request changes
         * @description Backend enforces reviewer identity different from author or generator.
         */
        post: operations["reviewAdminQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/{questionId}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Immediately retire unsafe content */
        post: operations["retireAdminQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/{questionId}/retire-request": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request an auditable retirement decision */
        post: operations["requestAdminQuestionRetirement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a DRAFT-only import without mutation */
        post: operations["previewAdminImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/imports/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit the exact DRAFT-only import preview */
        post: operations["commitAdminImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/bulk-status/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview safe bulk status transitions */
        post: operations["previewAdminBulkStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/bulk-status/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit the exact safe bulk status preview */
        post: operations["commitAdminBulkStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read correlated immutable admin audit history */
        get: operations["listAdminAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Meta: {
            request_id: string;
            /** @constant */
            api_version: "v1";
        };
        Page: {
            page_size: number;
            has_more: boolean;
            next_cursor: string | null;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                fields: {
                    [key: string]: string[];
                };
                request_id: string;
            };
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name?: string | null;
            /**
             * @default fa-IR
             * @enum {string}
             */
            locale: "fa-IR" | "en-CA";
            /** @default UTC */
            timezone: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name?: string | null;
            roles: ("USER" | "ADMIN" | "CONTENT_EDITOR" | "REVIEWER")[];
        };
        AuthToken: {
            readonly access_token: string;
            /** @constant */
            token_type: "Bearer";
            expires_in: number;
            /** Format: uuid */
            session_id: string;
        };
        UserEnvelope: {
            data: components["schemas"]["User"];
            meta: components["schemas"]["Meta"];
        };
        AuthTokenEnvelope: {
            data: components["schemas"]["AuthToken"];
            meta: components["schemas"]["Meta"];
        };
        Subtopic: {
            /** Format: uuid */
            id: string;
            code: string;
            title_fr: string;
            title_fa?: string | null;
            short_definition_fa?: string | null;
            active: boolean;
        };
        Lesson: {
            /** Format: uuid */
            id: string;
            lesson_no: number;
            title_fr: string;
            short_title: string;
            /** Format: uuid */
            category_id: string;
            /** Format: uuid */
            subcategory_id: string;
            category_title_fr?: string;
            category_title_fa?: string | null;
            subcategory_title_fr?: string;
            subcategory_title_fa?: string | null;
            tcf_weight?: number;
            active: boolean;
            question_count: number;
        };
        LessonDetail: {
            /** Format: uuid */
            id: string;
            lesson_no: number;
            title_fr: string;
            short_title: string;
            /** Format: uuid */
            category_id: string;
            /** Format: uuid */
            subcategory_id: string;
            category_title_fr?: string;
            category_title_fa?: string | null;
            subcategory_title_fr?: string;
            subcategory_title_fa?: string | null;
            tcf_weight?: number;
            active: boolean;
            question_count: number;
            subtopics: components["schemas"]["Subtopic"][];
        };
        LessonCollectionEnvelope: {
            data: components["schemas"]["Lesson"][];
            page: components["schemas"]["Page"];
            meta: components["schemas"]["Meta"];
        };
        LessonDetailEnvelope: {
            data: components["schemas"]["LessonDetail"];
            meta: components["schemas"]["Meta"];
        };
        /** @enum {string} */
        Difficulty: "EASY" | "MEDIUM" | "HARD" | "VERY_HARD";
        /** @enum {string} */
        QuestionStatus: "DRAFT" | "READY_FOR_REVIEW" | "CHANGES_REQUESTED" | "APPROVED" | "PUBLISHED" | "REJECTED" | "RETIRED";
        TestCreateRequest: {
            /** @enum {string} */
            schema_version: "test-config-schema-v0.9.0" | "adaptive-selection-config-v0.9.0";
            /** @enum {string} */
            mode: "custom" | "tcf" | "adaptive" | "review" | "mistakes";
            question_count: number;
            scope: {
                [key: string]: unknown;
            };
            difficulty_mix_pct: {
                EASY: number;
                MEDIUM: number;
                HARD: number;
                VERY_HARD: number;
            };
            lesson_allocation?: {
                [key: string]: unknown;
            };
            type_allocation?: {
                [key: string]: unknown;
            };
            seed?: string | null;
        };
        Test: {
            /** Format: uuid */
            id: string;
            mode: string;
            title?: string | null;
            question_count: number;
            selection_model_version?: string;
            /** Format: date-time */
            created_at: string;
        };
        TestEnvelope: {
            data: components["schemas"]["Test"];
            meta: components["schemas"]["Meta"];
        };
        Attempt: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            test_id: string;
            /** @enum {string} */
            status: "IN_PROGRESS" | "COMPLETED" | "ABANDONED";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at?: string | null;
            score_raw?: number | null;
            score_pct?: number | null;
        };
        AttemptEnvelope: {
            data: components["schemas"]["Attempt"];
            meta: components["schemas"]["Meta"];
        };
        AttemptOption: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            position: "A" | "B" | "C" | "D";
            text: string;
        };
        /** @description Pre-answer allow-list; intentionally has no correct option or explanation fields. */
        AttemptQuestion: {
            /** Format: uuid */
            test_question_id: string;
            /** Format: uuid */
            question_revision_id: string;
            position: number;
            stem: string;
            /** @enum {string} */
            stem_locale: "fr-FR" | "fa-IR";
            question_type: string;
            difficulty: components["schemas"]["Difficulty"];
            options: components["schemas"]["AttemptOption"][];
            media?: {
                /** @enum {string} */
                type: "IMAGE" | "AUDIO" | "VIDEO";
                /** Format: uri-reference */
                uri: string;
                alt_text?: string | null;
                transcript?: string | null;
            }[];
        };
        AttemptQuestionEnvelope: {
            data: components["schemas"]["AttemptQuestion"];
            meta: components["schemas"]["Meta"];
        };
        AnswerRequest: {
            /** Format: uuid */
            test_question_id: string;
            /** Format: uuid */
            selected_option_id: string;
            response_ms?: number | null;
        };
        AnswerFeedback: {
            is_correct: boolean;
            /** Format: uuid */
            selected_option_id: string;
            /** Format: uuid */
            correct_option_id: string;
            selected_option_explanation?: string | null;
            correct_option_explanation?: string | null;
            full_explanation?: string | null;
        };
        AnswerReceipt: {
            /** Format: uuid */
            answer_id: string;
            /** Format: uuid */
            attempt_id: string;
            /** Format: uuid */
            test_question_id: string;
            /** Format: date-time */
            answered_at: string;
            feedback: components["schemas"]["AnswerFeedback"];
            mastery: components["schemas"]["MasteryItem"];
            /** Format: uuid */
            review_item_id?: string | null;
            review_schedule: {
                [key: string]: unknown;
            };
        };
        AnswerReceiptEnvelope: {
            data: components["schemas"]["AnswerReceipt"];
            meta: components["schemas"]["Meta"];
        };
        AttemptResult: {
            /** Format: uuid */
            attempt_id: string;
            /** @constant */
            status: "COMPLETED";
            score_raw: number;
            score_pct: number;
            /** Format: date-time */
            completed_at: string;
            breakdown: {
                /** Format: uuid */
                test_question_id: string;
                position: number;
                /** Format: uuid */
                answer_id: string;
                feedback: components["schemas"]["AnswerFeedback"];
            }[];
        };
        AttemptResultEnvelope: {
            data: components["schemas"]["AttemptResult"];
            meta: components["schemas"]["Meta"];
        };
        ReviewSummary: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "MISTAKE" | "SPACED";
            status: string;
            title: string;
            group_key?: string | null;
            repeat_count?: number;
            /** Format: date-time */
            due_at?: string | null;
            marked: boolean;
        };
        ReviewCollectionEnvelope: {
            data: components["schemas"]["ReviewSummary"][];
            page: components["schemas"]["Page"];
            meta: components["schemas"]["Meta"];
        };
        ReviewItem: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            resolution_status: "UNRESOLVED" | "CORRECTED" | "EXCLUDED_CONTENT_ISSUE";
            /** @enum {string} */
            reviewability: "RETRY_ALLOWED" | "HISTORY_ONLY";
            marked: boolean;
            /** @enum {string} */
            feedback_state: "HIDDEN" | "REVEALED";
            /** Format: uuid */
            previous_selected_option_id?: string | null;
            question: components["schemas"]["AttemptQuestion"];
        };
        ReviewItemEnvelope: {
            data: components["schemas"]["ReviewItem"];
            meta: components["schemas"]["Meta"];
        };
        ReviewGradeRequest: {
            /** Format: uuid */
            selected_option_id: string;
        };
        ReviewMarkRequest: {
            marked: boolean;
        };
        ReviewFeedbackEnvelope: {
            data: {
                review_item: components["schemas"]["ReviewItem"];
                feedback: components["schemas"]["AnswerFeedback"];
            };
            meta: components["schemas"]["Meta"];
        };
        MasteryItem: {
            /** @enum {string} */
            scope_type?: "SUBTOPIC" | "LESSON" | "CATEGORY" | "TAG";
            /** Format: uuid */
            scope_id?: string;
            scope_title?: string;
            mastery_score_pct: number;
            confidence: number;
            coverage_ratio: number;
            evidence_count?: number;
            /** @enum {string} */
            mastery_band: "NO_EVIDENCE" | "UNCERTAIN" | "WEAK" | "DEVELOPING" | "STRONG";
            model_version: string;
        };
        MasteryCollectionEnvelope: {
            data: components["schemas"]["MasteryItem"][];
            meta: components["schemas"]["Meta"];
        };
        ProgressPoint: {
            /** @enum {string} */
            scope_type: "SUBTOPIC" | "LESSON" | "CATEGORY" | "TAG";
            /** Format: uuid */
            scope_id: string;
            mastery_score_pct: number;
            confidence: number;
            coverage_ratio: number;
            evidence_count: number;
            /** @enum {string} */
            mastery_band: "NO_EVIDENCE" | "UNCERTAIN" | "WEAK" | "DEVELOPING" | "STRONG";
            model_version: string;
            /** Format: date-time */
            captured_at: string;
        };
        ProgressEnvelope: {
            data: {
                points: components["schemas"]["ProgressPoint"][];
                incomplete_data: boolean;
                warning?: string | null;
            };
            meta: components["schemas"]["Meta"];
        };
        DashboardEnvelope: {
            data: {
                /** Format: date-time */
                as_of: string;
                /** @enum {string} */
                next_action: "OVERDUE_REVIEW" | "DUE_REVIEW" | "CRITICAL_CONFIDENT_LESSON" | "WEAK_CONFIDENT_LESSON" | "DEVELOPING_LESSON" | "BUILD_EVIDENCE" | "REGULAR_PRACTICE";
                mastery: components["schemas"]["MasteryItem"][];
                review_queue: {
                    [key: string]: unknown;
                };
                error_review: {
                    [key: string]: unknown;
                };
                recent_test: {
                    [key: string]: unknown;
                } | null;
                in_progress_attempt: {
                    /** Format: uuid */
                    attempt_id: string;
                    /** Format: uuid */
                    test_id: string;
                    mode: string;
                    title?: string | null;
                    /** Format: date-time */
                    started_at: string;
                    question_count: number;
                    answered_count: number;
                } | null;
                trend: {
                    [key: string]: unknown;
                };
                activity: {
                    [key: string]: unknown;
                };
            };
            meta: components["schemas"]["Meta"];
        };
        NextActionEnvelope: {
            data: {
                code: string;
                destination: string;
                reason: string;
            };
            meta: components["schemas"]["Meta"];
        };
        AnalyticsJobRequest: {
            /** @enum {string} */
            job_type: "DASHBOARD_REBUILD" | "MASTERY_BACKFILL" | "PROGRESS_REBUILD" | "QUESTION_METRICS_REBUILD";
            input: {
                [key: string]: unknown;
            };
        };
        AnalyticsJob: {
            /** Format: uuid */
            id: string;
            job_type: string;
            /** @enum {string} */
            state: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
            progress_pct: number;
            /** Format: date-time */
            queued_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            error_code?: string | null;
            result?: {
                [key: string]: unknown;
            } | null;
        };
        AnalyticsJobEnvelope: {
            data: components["schemas"]["AnalyticsJob"];
            meta: components["schemas"]["Meta"];
        };
        QuestionOptionInput: {
            /** @enum {string} */
            position: "A" | "B" | "C" | "D";
            text: string;
            explanation: string;
            /** Format: uuid */
            misconception_id?: string | null;
        };
        QuestionDraftRequest: {
            external_id: string;
            /** Format: uuid */
            lesson_id: string;
            /** Format: uuid */
            primary_subtopic_id: string;
            question_type_code: string;
            stem: string;
            full_explanation: string;
            difficulty: components["schemas"]["Difficulty"];
            /** @enum {string} */
            source_type: "BOOK_DIRECT" | "PROJECT_SYNTHETIC_FROM_RULE" | "EXTERNAL_REVIEWED";
            source_ref: string;
            /** @enum {string} */
            correct_option_position: "A" | "B" | "C" | "D";
            options: components["schemas"]["QuestionOptionInput"][];
            /** @constant */
            status?: "DRAFT";
        };
        QuestionRevisionRequest: {
            stem?: string;
            full_explanation?: string;
            difficulty?: components["schemas"]["Difficulty"];
            source_ref?: string;
            /** @enum {string} */
            correct_option_position?: "A" | "B" | "C" | "D";
            options?: components["schemas"]["QuestionOptionInput"][];
        };
        QuestionReviewRequest: {
            /** @enum {string} */
            action: "APPROVE" | "REJECT" | "REQUEST_CHANGES";
            notes?: string | null;
            reason_codes?: string[];
        };
        RetirementRequest: {
            reason: string;
            /** Format: uuid */
            source_report_id?: string | null;
        };
        AdminQuestion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            question_uid: string;
            revision: number;
            status: components["schemas"]["QuestionStatus"];
            /** Format: uuid */
            author_actor_id: string;
            /** Format: uuid */
            reviewer_actor_id?: string | null;
            quality_metrics?: {
                [key: string]: unknown;
            } | null;
            metric_sample_size?: number;
        } & {
            [key: string]: unknown;
        };
        AdminQuestionEnvelope: {
            data: components["schemas"]["AdminQuestion"];
            meta: components["schemas"]["Meta"];
        };
        AdminQuestionCollectionEnvelope: {
            data: components["schemas"]["AdminQuestion"][];
            page: components["schemas"]["Page"];
            meta: components["schemas"]["Meta"];
        };
        ImportRow: components["schemas"]["QuestionDraftRequest"] & {
            /** @constant */
            status: "DRAFT";
        };
        ImportPreviewRequest: {
            /** @constant */
            schema_version: "stage20-bulk-import-v1.0.0";
            /** Format: uuid */
            batch_id: string;
            rows: components["schemas"]["ImportRow"][];
        };
        BulkStatusPreviewRequest: {
            /** Format: uuid */
            batch_id: string;
            question_ids: string[];
            /** @enum {string} */
            target_status: "DRAFT" | "READY_FOR_REVIEW" | "CHANGES_REQUESTED";
        };
        CommitPreviewRequest: {
            /** Format: uuid */
            batch_id: string;
            confirmation_token: string;
        };
        PreviewEnvelope: {
            data: {
                /** Format: uuid */
                batch_id: string;
                valid_count: number;
                rejected_count: number;
                errors?: {
                    [key: string]: unknown;
                }[];
                confirmation_token: string;
            };
            meta: components["schemas"]["Meta"];
        };
        AuditCollectionEnvelope: {
            data: ({
                /** Format: uuid */
                id: string;
                canonical_audit_log_id?: number;
                action: string;
                resource_type: string;
                /** Format: uuid */
                resource_id?: string | null;
                request_id?: string | null;
                /** Format: date-time */
                occurred_at: string;
            } & {
                [key: string]: unknown;
            })[];
            page: components["schemas"]["Page"];
            meta: components["schemas"]["Meta"];
        };
        GenericEnvelope: {
            data: {
                [key: string]: unknown;
            };
            meta: components["schemas"]["Meta"];
        };
    };
    responses: {
        /** @description Query parameter invalid */
        BadQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required or token/session invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authenticated principal lacks permission */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource absent or concealed owner mismatch */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description State or idempotency conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request validation or safe inventory failure */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Versioned rate limit exceeded */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Required dependency unavailable */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        PageSize: number;
        PageAfter: string;
        Sort: string;
        LessonId: string;
        TestId: string;
        AttemptId: string;
        ReviewId: string;
        JobId: string;
        QuestionId: string;
    };
    requestBodies: never;
    headers: {
        /** @description True when the stored response was replayed for the same key and request hash */
        IdempotentReplayed: boolean;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Learner registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
            429: components["responses"]["RateLimited"];
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Validation"];
            429: components["responses"]["RateLimited"];
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listLessons: {
        parameters: {
            query?: {
                "page[size]"?: components["parameters"]["PageSize"];
                "page[after]"?: components["parameters"]["PageAfter"];
                sort?: components["parameters"]["Sort"];
                "filter[category_id]"?: string;
                "filter[tag_id]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lesson page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonCollectionEnvelope"];
                };
            };
            400: components["responses"]["BadQuery"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: components["parameters"]["LessonId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lesson detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetailEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createTest: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCreateRequest"];
            };
        };
        responses: {
            /** @description Test snapshot created */
            201: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    getTest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                testId: components["parameters"]["TestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    startAttempt: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                testId: components["parameters"]["TestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attempt started */
            201: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getNextAttemptQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next question */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptQuestionEnvelope"];
                };
            };
            /** @description No unanswered question remains */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    submitAttemptAnswer: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                attemptId: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Answer accepted; feedback applies only to this item */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerReceiptEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
            429: components["responses"]["RateLimited"];
        };
    };
    completeAttempt: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                attemptId: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attempt completed */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getAttemptResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed result and item feedback */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResultEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listReviews: {
        parameters: {
            query?: {
                "page[size]"?: components["parameters"]["PageSize"];
                "page[after]"?: components["parameters"]["PageAfter"];
                sort?: components["parameters"]["Sort"];
                "filter[kind]"?: "MISTAKE" | "SPACED";
                "filter[resolution_status]"?: "UNRESOLVED" | "CORRECTED" | "EXCLUDED_CONTENT_ISSUE";
                "filter[marked]"?: boolean;
                "filter[due]"?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCollectionEnvelope"];
                };
            };
            400: components["responses"]["BadQuery"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getReviewItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review item without a premature answer key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    gradeReview: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                reviewId: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewGradeRequest"];
            };
        };
        responses: {
            /** @description Retry graded and review state updated */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewFeedbackEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    revealReviewAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feedback revealed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewFeedbackEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    setReviewMark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewMarkRequest"];
            };
        };
        responses: {
            /** @description Mark state updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getMastery: {
        parameters: {
            query?: {
                "filter[scope_type]"?: "SUBTOPIC" | "LESSON" | "CATEGORY" | "TAG";
                "filter[scope_id]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current mastery resources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasteryCollectionEnvelope"];
                };
            };
            400: components["responses"]["BadQuery"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getProgress: {
        parameters: {
            query?: {
                "filter[scope_type]"?: "SUBTOPIC" | "LESSON" | "CATEGORY" | "TAG";
                "filter[scope_id]"?: string;
                "filter[from]"?: string;
                "filter[to]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted progress series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressEnvelope"];
                };
            };
            400: components["responses"]["BadQuery"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stage 18 dashboard summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    getCurrentNextAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One action selected by the Stage 18 priority contract */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextActionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAnalyticsJob: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyticsJobRequest"];
            };
        };
        responses: {
            /** @description Job queued */
            202: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsJobEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    getAnalyticsJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsJobEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdminQuestions: {
        parameters: {
            query?: {
                "page[size]"?: components["parameters"]["PageSize"];
                "page[after]"?: components["parameters"]["PageAfter"];
                sort?: components["parameters"]["Sort"];
                "filter[lesson_id]"?: string;
                "filter[status]"?: components["schemas"]["QuestionStatus"];
                "filter[difficulty]"?: components["schemas"]["Difficulty"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Staff question-bank page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQuestionCollectionEnvelope"];
                };
            };
            400: components["responses"]["BadQuery"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAdminQuestionDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionDraftRequest"];
            };
        };
        responses: {
            /** @description Draft created and audited */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQuestionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Validation"];
            429: components["responses"]["RateLimited"];
        };
    };
    createAdminQuestionRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionRevisionRequest"];
            };
        };
        responses: {
            /** @description New revision created and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQuestionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
            429: components["responses"]["RateLimited"];
        };
    };
    reviewAdminQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionReviewRequest"];
            };
        };
        responses: {
            /** @description Dedicated review action recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQuestionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
            429: components["responses"]["RateLimited"];
        };
    };
    retireAdminQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetirementRequest"];
            };
        };
        responses: {
            /** @description Question retired; history preserved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQuestionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    requestAdminQuestionRetirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetirementRequest"];
            };
        };
        responses: {
            /** @description Retirement request queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    previewAdminImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportPreviewRequest"];
            };
        };
        responses: {
            /** @description Preview plus confirmation token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Validation"];
        };
    };
    commitAdminImport: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitPreviewRequest"];
            };
        };
        responses: {
            /** @description Exact preview committed atomically and audited */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    previewAdminBulkStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkStatusPreviewRequest"];
            };
        };
        responses: {
            /** @description Transition preview plus confirmation token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    commitAdminBulkStatus: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitPreviewRequest"];
            };
        };
        responses: {
            /** @description Safe transitions committed atomically and audited */
            200: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    listAdminAuditEvents: {
        parameters: {
            query?: {
                "page[size]"?: components["parameters"]["PageSize"];
                "page[after]"?: components["parameters"]["PageAfter"];
                sort?: components["parameters"]["Sort"];
                "filter[action]"?: string;
                "filter[resource_id]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Correlated Stage 12 and Stage 20 audit records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditCollectionEnvelope"];
                };
            };
            400: components["responses"]["BadQuery"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
