import json
import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "frontend"


class Stage22FrontendContractTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.contract = json.loads((ROOT / "config/stage22_frontend_contract_v1.0.json").read_text(encoding="utf-8"))
        cls.package = json.loads((FRONTEND / "package.json").read_text(encoding="utf-8"))
        cls.openapi = (ROOT / "api/stage21_core_api_spec_v1.0.yaml").read_text(encoding="utf-8")
        cls.frontend_sources = {
            path.relative_to(FRONTEND).as_posix(): path.read_text(encoding="utf-8")
            for path in FRONTEND.rglob("*")
            if path.is_file() and "node_modules" not in path.parts and ".next" not in path.parts
        }

    def test_owner_and_status_are_explicit(self):
        self.assertEqual(self.contract["stage"], 22)
        self.assertEqual(self.contract["governance"]["content_owner"], "Iman")
        self.assertEqual(self.contract["governance"]["technical_owner"], "Iman")
        self.assertIn("PENDING_OWNER_ACCEPTANCE", self.contract["release_status"])

    def test_selected_framework_matches_stage21_handoff(self):
        self.assertEqual(self.package["dependencies"]["next"], "16.2.11")
        self.assertEqual(self.package["dependencies"]["react"], "19.2.8")
        tsconfig = json.loads((FRONTEND / "tsconfig.json").read_text(encoding="utf-8"))
        self.assertTrue(tsconfig["compilerOptions"]["strict"])

    def test_five_required_runner_components_exist(self):
        for component in self.contract["required_components"]:
            self.assertTrue((FRONTEND / f"src/components/runner/{component}.tsx").is_file(), component)

    def test_pre_answer_openapi_projection_has_no_answer_key(self):
        match = re.search(r"\n    AttemptQuestion:\n(?P<body>.*?)(?=\n    AttemptQuestionEnvelope:)", self.openapi, re.S)
        self.assertIsNotNone(match)
        body = match.group("body")
        for forbidden in ("correct_option_id", "correct_option", "explanation", "is_correct", "answer_key"):
            self.assertNotRegex(body, rf"(?m)^\s+{forbidden}:\s*")
        self.assertIn("intentionally has no correct option", body)

    def test_generated_types_are_openapi_derived(self):
        generated = self.frontend_sources["src/lib/api/generated.ts"]
        aliases = self.frontend_sources["src/lib/api/types.ts"]
        self.assertIn("This file was auto-generated by openapi-typescript", generated)
        self.assertIn('paths["/attempts/{attemptId}/next"]', aliases)
        self.assertIn('components["schemas"]["AttemptQuestion"]', aliases)

    def test_browser_does_not_store_bearer_token(self):
        client_files = {
            path: text for path, text in self.frontend_sources.items()
            if (path.startswith("src/components/") or path.startswith("src/lib/offline/"))
            and ".test." not in path
        }
        combined = "\n".join(client_files.values())
        self.assertNotIn("localStorage", combined)
        self.assertNotIn("access_token", combined)
        login_route = self.frontend_sources["src/app/api/session/login/route.ts"]
        self.assertIn("httpOnly: true", login_route)
        self.assertIn('response.cookies.set("gmp_access_token"', login_route)

    def test_retry_store_excludes_sensitive_and_answer_key_fields(self):
        schema = json.loads((ROOT / "schemas/stage22_pending_answer_v1.0.json").read_text(encoding="utf-8"))
        self.assertFalse(schema["additionalProperties"])
        for forbidden in self.contract["network_resilience"]["forbidden_fields"]:
            self.assertNotIn(forbidden, schema["properties"])
        runner = self.frontend_sources["src/components/runner/AttemptRunner.tsx"]
        self.assertIn('"Idempotency-Key": record.idempotency_key', runner)
        self.assertIn("putPendingAnswer(record)", runner)

    def test_keyboard_touch_and_direction_controls_are_executable(self):
        runner = self.frontend_sources["src/components/runner/AttemptRunner.tsx"]
        option = self.frontend_sources["src/components/runner/Option.tsx"]
        css = self.frontend_sources["src/app/globals.css"]
        self.assertIn('/^[1-4]$/.test(event.key)', runner)
        self.assertIn('event.key === "Enter"', runner)
        self.assertIn('event.key.toLowerCase() === "n"', runner)
        self.assertIn('min-block-size: 56px', css)
        self.assertIn('<bdi dir="auto"', option)

    def test_all_stage19_canonical_routes_have_page_modules(self):
        expected = [
            "login", "register", "dashboard", "tests/new", "attempts/[attemptId]",
            "attempts/[attemptId]/result", "review", "lessons", "lessons/[lessonId]",
            "progress", "history", "profile", "settings",
        ]
        for route in expected:
            self.assertTrue((FRONTEND / f"src/app/[locale]/{route}/page.tsx").is_file(), route)

    def test_stage20_staff_routes_are_reserved_and_fail_closed(self):
        expected = [
            "questions", "questions/[questionId]", "reviews", "reviews/[questionId]",
            "imports", "questions/bulk-status", "audit",
        ]
        for route in expected:
            self.assertTrue((FRONTEND / f"src/app/staff/{route}/page.tsx").is_file(), route)
        staff = self.frontend_sources["src/components/staff/StaffSurface.tsx"]
        self.assertIn("Django must return 403", staff)

    def test_missing_page_resources_are_not_silently_invented(self):
        decision = next(item for item in self.contract["open_decisions"] if item["code"] == "S22_D03_MISSING_PAGE_RESOURCES")
        self.assertEqual(decision["status"], "NEEDS_STAGE21_API_REVISION_OR_SCOPE_DECISION")
        unavailable = self.frontend_sources["src/components/product/UnavailableSurface.tsx"]
        self.assertIn("no fabricated data", unavailable)

    def test_accessibility_and_responsive_evidence_exists(self):
        checklist = (ROOT / "docs/stages/stage22/accessibility_checklist_v1.0.md").read_text(encoding="utf-8")
        matrix = (ROOT / "docs/stages/stage22/responsive_state_matrix_v1.0.csv").read_text(encoding="utf-8")
        self.assertIn("WCAG 2.2 AA", checklist)
        self.assertIn("Screen-reader", checklist)
        for state in ("LOADING", "ERROR", "OFFLINE_RETRY", "UNAUTHORIZED"):
            self.assertIn(state, matrix)


if __name__ == "__main__":
    unittest.main()
